basePath: /api/v1
definitions:
  main.User:
    properties:
      email:
        type: string
      id:
        type: integer
      username:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: API for user management
  title: User API
  version: "1.0"
paths:
  /users:
    get:
      description: Get all users
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/main.User'
            type: array
      summary: Get all users
    post:
      consumes:
      - application/json
      description: Create a user
      parameters:
      - description: User ID
        in: path
        name: ID
        required: true
        type: integer
      - description: Username
        in: path
        name: Username
        required: true
        type: string
      - description: Email
        in: path
        name: Email
        required: true
        type: string
      produces:
      - application/json
      responses:
        "201":
          description: Created
      summary: Create a user
  /users/{id}:
    delete:
      description: Delete a user by ID
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: OK
      summary: Delete a user
    put:
      consumes:
      - application/json
      description: Update a user by ID
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      - description: User object
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/main.User'
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Update a user
swagger: "2.0"
